### ISSUE TITLE
Entities refactoring

### ISSUE THREAD

**Issue by zhil** [thecatontheflat/atlassian-marketplace-tools#34] opened 2017-03-24 10:40 UTC
Current entity structure could be optimized. Like
* add Addon entity, remove addonName/addonKey from Licence, link addon instead
* move company/contacts into entities Company, Contact, link Licence to them instead of raw fields
* store all data, which json provide
etc

it could simplify some tasks (like get ALL licences for some company etc), but it would also bring BC break on database level.

As I understand, you could simply reset database and load it again in new structure.

@thecatontheflat 
I am going to work on this change - will you accept such a PR?

**Comment by thecatontheflat** [comment] 2017-03-24 11:24
Hey,
that would be great!

Don't bother too much with BC — you are right, the project is built in a way that the DB can be just re-created.

**Comment by zhil** [comment] 2017-03-24 11:40
@thecatontheflat 
ok, cool

just checking - current implementation use v1 api, which return csv file
could I change everything to v2 api, which return json and remove csv stuff?

**Comment by thecatontheflat** [comment] 2017-03-24 12:36
@zhil this would be SUPER AWESOME! :)

**Comment by zhil** [comment] 2017-03-24 20:01
@thecatontheflat 
quick question. In LicenceRepository there is function
https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/src/AppBundle/Entity/LicenseRepository.php#L84
```
public function findForEvent(Event $event)
```
Its not uses anywhere, also it seems to use undefined entity Event.
Could I just remove it?

**Comment by thecatontheflat** [comment] 2017-03-24 20:03
@zhil 

Yeah, seems to be an old leftover. Feel free to purge it 😈

**Comment by zhil** [comment] 2017-03-24 20:07
ok
* $licenseId in License entity seems to be unique and could be used to identify licence on atlassian side?
* LicenseFactory.php seems to be not used?

**Comment by thecatontheflat** [comment] 2017-03-24 20:12
`$licenseId` contains SEN, which is not unique. There could be multiple entries with the same SEN (per Add-On).

For example:
![reports_-_lizard_brain_ug___atlassian_marketplace](https://cloud.githubusercontent.com/assets/727581/24311905/754c4fd8-10d6-11e7-876f-dbc23fe00d2c.jpg)

Regarding `LicenseFactory` — I would assume that it was used in tests, but couldn't find it too.

**Comment by zhil** [comment] 2017-03-24 20:18
json api provide actually 3 ids https://developer.atlassian.com/market/api/2/reference/resource/vendors/%7BvendorId%7D/reporting/licenses
```
addonLicenseId string 
The unique identifier for this license, for example "12345"
hostLicenseId string
The unique identifier for this host instance, for example "12345". Applies to cloud licenses only
licenseId string 
The customer-facing identifier for this license, for example "SEN-12345"
```
not sure, which one field is represented with current License->licenceId, but probably we could use addonLicenseId as unique identifier?

![image](https://cloud.githubusercontent.com/assets/981783/24312048/7bf8a2ec-10df-11e7-8727-58fd89f6eebc.png)

**Comment by thecatontheflat** [comment] 2017-03-24 20:22
@zhil Yeah, it seems to be unique — let's use it.

**Comment by zhil** [comment] 2017-03-24 20:34
@thecatontheflat as I understand, you also had some kind of event based email scheduler in repository?
Did you decided to use MailChimp instead?

**Comment by thecatontheflat** [comment] 2017-03-24 20:56
@zhil 
Correct — there was a scheduler initially, but I decided to remove this functionality and to keep the project simply for reporting purposes and for receiving email notifications about the new sales.

Here is the commit with the cleanups:
https://github.com/thecatontheflat/atlassian-vendor-tools/commit/99ef1856c7a71d3fa7b931c64800a236ecc881c7

MailChimp is used for subscribing customers to the mailing list feature, during the license import.

**Comment by zhil** [comment] 2017-03-24 20:59
@thecatontheflat I see. So you moved that to another repo or using MailChimp for that?

~~btw, I got SQL error on dashboard, could it be mysql version problem?~~
got it. sql_mode=only_full_group_by

![image](https://cloud.githubusercontent.com/assets/981783/24313426/6817e566-10e5-11e7-96c5-fed5d53024f7.png)

**Comment by thecatontheflat** [comment] 2017-03-24 21:03
@zhil 

I am not sure regarding SQL error. Seems like some configuration flag.

Regarding MailChimp — I didn't get the question.
The "scheduler" functionality (`mandrill` initially) was removed completely. The "subscribe" functionality is still there and it uses MailChimp:
https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/src/AppBundle/Command/ImportLicenseCommand.php#L56

**Comment by zhil** [comment] 2017-03-24 21:11
@thecatontheflat 

well, I planned to create some kind scheduler for emails, which would send emails based on some event, like 
* new user registered - "welcome" email
* user registered, tried plugin, but stop using it completely - "Did you get problems?" email
etc.

"Drill" system looks like the same concept - so I just wonder why did you decided to remove it. I never used mailchimp before - did you decided to use mailchimp instead of own system?

**Comment by thecatontheflat** [comment] 2017-03-24 21:22
@zhil 

Exactly. I switched to MailChimp for described tasks, because it simply does this job better. Especially the drilling. It has a decent automation, nice editor etc. In general, I preferred to use a system that was designed specifically for such tasks instead of trying to implement such system on my own.

I figured that those kind of events (when they are based on the license data *only*) are quite ineffective as compared to the approach when you actually analyse your data (not just licenses, but the add-ons interaction etc.) and then manually contact your prospects.

**Comment by zhil** [comment] 2017-03-24 22:03
@thecatontheflat ok, got you. thanks for explanation.

**Comment by zhil** [comment] 2017-03-24 22:16
@thecatontheflat one more question
as I understand, sale entity represent transactions https://developer.atlassian.com/market/api/2/reference/resource/vendors/%7BvendorId%7D/reporting/sales/transactions

cant find discounted property - what does it mean?

**Comment by thecatontheflat** [comment] 2017-03-24 23:56
According to my database, looks like this property was always set for annual sales. I couldn't find it in the transaction json, so I guess it can be removed.

**Comment by zhil** [comment] 2017-03-25 12:21
quick question regarding code.
not sure how could this work https://github.com/thecatontheflat/atlassian-vendor-tools/blob/master/src/AppBundle/Entity/LicenseRepository.php#L109
```
public function findExpiringSoon()
    {
        $result = $this->createQueryBuilder('l')
            ->where('DATE_DIFF(l.endDate, CURRENT_DATE()) <= ?1')
            ->andWhere('DATE_DIFF(l.endDate, CURRENT_DATE()) >= ?2')
            ->orderBy('l.endDate', 'DESC')
            ->setParameter('1', 5)
            ->setParameter('2', 0)
            ->getQuery()
            ->getResult();

        return $result;
    }
```

**Comment by zhil** [comment] 2017-03-25 13:03
@thecatontheflat looks like it would take more time, as I have expected :)

I have created "work-in-progress" PR, let me know if I am moving in right directions and if you have some suggestions.
https://github.com/thecatontheflat/atlassian-vendor-tools/pull/35

json processing will need to be refactored sometime, probably it could be done later.

**Comment by zhil** [comment] 2017-03-25 15:39
@thecatontheflat 
entites and data import should already be working in pr #35 - can you please clone it, setup blank database and check if import is working for your data-set without exceptions?

**Comment by zhil** [comment] 2017-03-25 21:59
@thecatontheflat quick question.
Cant find edition of license in https://developer.atlassian.com/market/api/2/reference/resource/vendors/%7BvendorId%7D/reporting/licenses
In my data set it always have value "Subscription".

What does that property means? Could it be skipped?

**Comment by zhil** [comment] 2017-03-25 22:01
also current license view url contain SEN http://127.0.0.1:8000/license/SEN-9355321
so, probably, that should be named company page?
Also could SEN be used to identify company?

**Comment by zhil** [comment] 2017-03-27 11:29
@thecatontheflat can you please check questions above?

**Comment by thecatontheflat** [comment] 2017-03-27 11:36
- Regarding "Subscription" — no idea.
- SEN as a company ID — I am not sure, probably yes. I remember that Initially I thought SEN ought to be unique per license. It turned to be rather unique per organisation. Currently in the Marketplace Reports, when you click on the SEN it would just filter transactions with this number. It is possible to have multiple add-ons per same SEN number, but the company seems to be the same.
- Renaming the view — yes, I think company page makes more sense!

**Comment by zhil** [comment] 2017-03-27 11:40
Ok, thanks for explanation

Si what shoul I do with subscription field? Remove it?

**Comment by thecatontheflat** [comment] 2017-03-27 11:45
Yeah, feel free to remove everything you can't find use for :)

It seems that for now there is no use for this data in the Marketplace Reports, but I think it is reserved for the tier display in the future:

![reports_-_lizard_brain_ug___atlassian_marketplace_2](https://cloud.githubusercontent.com/assets/727581/24354779/80baf42c-12f3-11e7-9964-6ac157d0406a.jpg)

Regarding the SEN, here is some more data from my reports (same company, same SEN, multiple add-ons):

![reports_-_lizard_brain_ug___atlassian_marketplace](https://cloud.githubusercontent.com/assets/727581/24354823/b009223a-12f3-11e7-8be0-0d35342a6b3c.jpg)

**Comment by thecatontheflat** [comment] 2017-04-14 12:16
PR merged, closing this issue?

**Closed as completed by thecatontheflat** 2017-04-14 12:16 UTC

**Comment by zhil** [comment] 2017-04-14 12:25
@thecatontheflat yep

you will need also to create https://thecatontheflat.github.io/atlassian-vendor-tools.json - it will be used in checking updates

**Comment by thecatontheflat** [comment] 2017-04-14 12:26
👍
